### ISSUE TITLE
How to get data into ISY email

### ISSUE THREAD

**Issue by macjeff** [ve7gel/Timedata#1]
I installed the server.  If gives you data like Day of the Week and Season.

So lets say I want an email every day that says its DAY OF THE WEEK and its SEASON.

How can I get the data into email?

The only way I see is assign season and day of the week to variables but they are numbers.  So season would be 1-4 for spring summer winter fall and day of the week would be 1-7. 

So I can write a bunch of programs I guess to figure out which email to send but is there not a better way to dump that info into an email?

I found this command but no idea how to format it for this use.  

${sys.node.#.name}
 

The node address is n014_timedata
 

For example data I want out is called Season .    There are others.  I know I could convert to a variable number or there has to be a way to get 

So how would I format that to get the data out or am I using the wrong place?  (if thats even the correct command)

**Comment by ve7gel** [comment]
Try reading through this to see if you can find what you need:
`https://wiki.universal-devices.com/index.php?title=ISY-994i_Series:EMail_and_Networking_Substitution_Variables`
