### ISSUE TITLE
Sunrise time minutes issue when 00

### ISSUE THREAD

**Issue by macjeff** [ve7gel/Timedata#5]
Sorry Gordon but I found a minor bug.   Your MINUTES for sunrise and sunset work great except for one thing.  When its on the hour it gives you 0 instead of 00.   So my time went

sunset
5:58pm 2 days ago
5:59pm yesterday
and today 6:0pm 
so can you add the extra zero.

Sorry but as many others have pointed out I seem to attract bugs.

Thanks again for a great node server!!!   Your time and efforts are very much appreciated.

**Comment by ve7gel** [comment]
Sorry Jeff, it's not a bug.  It's the way the ISY works.  It cannot accept leading zeroes.

**Comment by macjeff** [comment]
I can fix it with a program

If sunset time minutes (field name) is zero then set MinutesVariable to 00
Else set MinutesVariable to sunset time minutes (field name).

and same for Sunrise.   Not a big deal.

I noticed you re-opened it.  If it was just for me to comment you can close this but otherwise let me know and I will monitor.

thanks again

**Comment by macjeff** [comment]
Update- I dont think the variable can handle leadiung zero either so I will have to write another program to split the minutes into two digits and then I can put minutes together when sending an email which is my goal.  Thats more work but doable.

**Comment by ve7gel** [comment]
There is a way to display the items as indices, but then the numerical comparisons don't work, so I have to leave it this way.

**Comment by macjeff** [comment]
Ok closing now.

**Comment by macjeff** [comment]
I have a program to fix this if anyone needs it.  Works great and puts 00 for the time.

**Comment by ve7gel** [comment]
You should post this on the UDI forum, not here.
