### ISSUE TITLE
Sunset Time (today and tomorrow) off by an hour

### ISSUE THREAD

**Issue by macjeff** [ve7gel/Timedata#6]
Sorry but found another bug.....

I swore it was right recently but now its off.  It just swtiched from after 6pm until before 6 pm so maybe thats the reason or a recent update in your node server caused it.

My location is 39.152380,-77.666940

See sunset time here:  5:59 tonight and 

https://keisan.casio.com/exec/system/1224686065

I am showing 18 as the time which is 6 pm.  It should be 17 both for tonight and tomorrow night.

See screenshots....
<img width="1311" alt="Screen Shot 2020-02-26 at 2 24 07 PM" src="https://user-images.githubusercontent.com/20373758/75380865-cf5c4400-58a5-11ea-8df4-640c3b67c6c3.png">
<img width="1017" alt="Screen Shot 2020-02-26 at 2 25 33 PM" src="https://user-images.githubusercontent.com/20373758/75380867-cf5c4400-58a5-11ea-9c48-d7d220bd8daf.png">

**Comment by ve7gel** [comment]
Not sure what that's about.  Mine is correct.  Must be something related to rounding somewhere.  There have been no changes to the nodeserver code since Feb. 17, only the profiles have changed.  I'll tinker with it when I get some time.

**Comment by macjeff** [comment]
I think the ISY is wrong and that is confusing me.

See screenshot but asking Siri tells me 6pm tonight and 6:01 tomorrow so I think you are correct.  Checking more sources.  Will close in a minute.  Sorry for false alarm.

<img width="522" alt="Screen Shot 2020-02-26 at 2 53 46 PM" src="https://user-images.githubusercontent.com/20373758/75382083-d5ebbb00-58a7-11ea-9820-a60accab4530.png">

**Comment by ve7gel** [comment]
Well, that's only a 2 or 3 minute difference you're talking about, which is easily within the error of margin when variations in algorithms and rounding methodologies is taken into account.  My ISY also shows a slightly different time, as do two other programs I use from other developers.  None of the 4 agree exactly.

**Comment by macjeff** [comment]
You are correct so I was seeing the 5:58pm on iSY and the hour variable on yours was 18 so I thought it was off but those 2 min was the difference

Sorry
